const lessons = [
  {id:'materia',n:'01',title:'Matéria: observar e classificar',time:'35 min',bncc:'EM13CNT101',summary:'Propriedades, estados físicos, substâncias e misturas a partir de situações cotidianas.',body:`<p>A Química investiga a composição, as propriedades e as transformações da matéria. Massa e volume são propriedades gerais; densidade, pontos de fusão e ebulição ajudam a identificar materiais.</p><h3>Do visível ao particulado</h3><p>Um copo com água e sal parece uniforme, mas é uma mistura. O modelo particulado explica fenômenos que os olhos não alcançam: as partículas continuam presentes e interagindo.</p><div class="question"><b>Investigue:</b> por que o óleo forma uma fase separada da água? Formule uma hipótese usando polaridade, sem realizar misturas perigosas.</div><h3>Exercícios propostos</h3><ol><li>Diferencie substância pura e mistura usando dois exemplos domésticos.</li><li>Explique por que densidade não depende apenas da massa.</li><li>Classifique: ar atmosférico, água destilada e granito.</li></ol>`},
  {id:'atomo',n:'02',title:'Átomos e modelos científicos',time:'45 min',bncc:'EM13CNT201',summary:'Como evidências modificaram as ideias de Dalton, Thomson, Rutherford, Bohr e o modelo quântico.',body:`<p>Modelos científicos não são fotografias da realidade: são construções que explicam evidências e permitem previsões. Dalton descreveu átomos como unidades; Thomson evidenciou o elétron; Rutherford mostrou um núcleo pequeno e positivo.</p><h3>Bohr e o modelo atual</h3><p>Bohr propôs níveis quantizados de energia. O modelo quântico abandona órbitas planetárias rígidas e descreve regiões de probabilidade chamadas orbitais.</p><div class="question"><b>Analise:</b> se o experimento de Rutherford mostrou que a maioria das partículas atravessava a lâmina, o que isso sugere sobre o espaço no átomo?</div><h3>Exercícios propostos</h3><ol><li>Associe cada modelo à evidência que o sustentou.</li><li>Calcule prótons, nêutrons e elétrons de <sup>23</sup>Na<sup>+</sup>.</li><li>Explique o limite da expressão “elétron orbitando”.</li></ol>`},
  {id:'periodica',n:'03',title:'Tabela periódica e ligações',time:'50 min',bncc:'EM13CNT104',summary:'Periodicidade, elétrons de valência, ligações e relação estrutura–propriedade.',body:`<p>A tabela organiza os elementos por número atômico. Elementos do mesmo grupo compartilham padrões de elétrons de valência, o que ajuda a prever reatividade.</p><h3>Por que os átomos se ligam?</h3><p>Ligações iônicas envolvem atração entre íons; covalentes envolvem compartilhamento eletrônico; metálicas explicam propriedades coletivas dos metais. Essas categorias são modelos, não caixas absolutas.</p><div class="question"><b>Compare:</b> por que NaCl conduz corrente quando fundido ou dissolvido, mas não no estado sólido?</div><h3>Exercícios propostos</h3><ol><li>Preveja o íon mais comum de Mg e Cl.</li><li>Represente a estrutura de Lewis de H₂O.</li><li>Relacione ligação metálica e condutividade.</li></ol>`},
  {id:'reacoes',n:'04',title:'Reações e estequiometria',time:'55 min',bncc:'EM13CNT101',summary:'Evidências de reação, conservação da massa, mol, balanceamento e rendimento.',body:`<p>Uma equação química registra reagentes, produtos e proporções. Balancear não cria partículas: ajusta coeficientes para representar a conservação dos átomos.</p><h3>Do mol à massa</h3><p>O mol conecta o mundo microscópico ao laboratório. Um mol contém aproximadamente 6,022 × 10²³ entidades. A massa molar permite converter quantidade de matéria em massa.</p><div class="question"><b>Resolva:</b> na reação 2 H₂ + O₂ → 2 H₂O, quantos mols de água podem surgir de 3 mols de O₂ com H₂ em excesso?</div><h3>Exercícios propostos</h3><ol><li>Balanceie Fe + O₂ → Fe₂O₃.</li><li>Calcule a massa molar do CO₂.</li><li>Diferencie reagente limitante e reagente em excesso.</li></ol>`},
  {id:'solucoes',n:'05',title:'Soluções, acidez e ambiente',time:'50 min',bncc:'EM13CNT105',summary:'Concentração, pH, neutralização, tratamento de água e impactos socioambientais.',body:`<p>Soluções têm soluto e solvente. A concentração pode ser expressa de diferentes maneiras e sempre exige unidade. O pH é uma escala logarítmica relacionada à atividade de íons H⁺.</p><h3>Química e direito à água</h3><p>Coagulação, floculação, decantação, filtração e desinfecção cumprem funções diferentes no tratamento. Água transparente não é necessariamente potável.</p><div class="question"><b>Argumente:</b> por que “natural” não significa automaticamente “seguro” em alimentos, águas ou produtos?</div><h3>Exercícios propostos</h3><ol><li>Calcule a concentração comum de 10 g em 500 mL.</li><li>Compare qualitativamente pH 3 e pH 5.</li><li>Pesquise a função de cada etapa de uma ETA local.</li></ol>`},
  {id:'energia',n:'06',title:'Energia, cinética e tecnologia',time:'55 min',bncc:'EM13CNT106',summary:'Calor de reação, velocidade, equilíbrio, eletroquímica e decisões tecnológicas.',body:`<p>Reações exotérmicas transferem energia ao ambiente; endotérmicas absorvem. A velocidade depende de fatores como temperatura, concentração, superfície de contato e catalisador.</p><h3>Pilhas e sociedade</h3><p>Pilhas convertem energia química em elétrica por reações de oxirredução. Sua produção e descarte envolvem recursos minerais, trabalho, tecnologia e impactos ambientais.</p><div class="question"><b>Avalie:</b> aumentar a temperatura sempre é a melhor forma de acelerar um processo industrial? Considere energia, segurança e seletividade.</div><h3>Exercícios propostos</h3><ol><li>Explique como um catalisador altera a energia de ativação.</li><li>Identifique oxidação e redução em Zn + Cu²⁺ → Zn²⁺ + Cu.</li><li>Proponha critérios para comparar duas tecnologias de bateria.</li></ol>`}
];

const elements=[
  {s:'H',name:'Hidrogênio',clue:'Sou o elemento mais abundante do Universo e tenho número atômico 1.'},
  {s:'C',name:'Carbono',clue:'Faço quatro ligações com frequência e formo a base das moléculas orgânicas.'},
  {s:'O',name:'Oxigênio',clue:'Tenho número atômico 8 e participo da respiração e de muitas combustões.'},
  {s:'Na',name:'Sódio',clue:'Sou um metal alcalino; meu cátion aparece no sal de cozinha.'},
  {s:'Fe',name:'Ferro',clue:'Meu símbolo vem do latim ferrum e sou central na siderurgia e na hemoglobina.'},
  {s:'Cl',name:'Cloro',clue:'Sou um halogênio e meu ânion forma cloretos.'},
  {s:'Si',name:'Silício',clue:'Sou metaloide importante em semicondutores e apareço em silicatos.'},
  {s:'Ca',name:'Cálcio',clue:'Meu íon 2+ participa de ossos, dentes e sinalização celular.'}
];

const questions=[
  ['Qual propriedade relaciona massa e volume?',['Densidade','Temperatura','Pressão','Solubilidade'],0,'matéria'],
  ['Uma mistura com uma única fase visível é chamada de:',['heterogênea','homogênea','substância simples','elemento'],1,'matéria'],
  ['O número atômico corresponde ao número de:',['nêutrons','núcleons','prótons','orbitais'],2,'átomo'],
  ['Um cátion é formado quando um átomo:',['ganha prótons','perde elétrons','ganha nêutrons','perde prótons'],1,'átomo'],
  ['O modelo que introduziu um núcleo pequeno e positivo foi o de:',['Dalton','Thomson','Rutherford','Arrhenius'],2,'átomo'],
  ['Elementos no mesmo grupo tendem a apresentar:',['igual massa','propriedades semelhantes','mesmo número atômico','igual número de camadas'],1,'tabela'],
  ['Na ligação covalente ocorre principalmente:',['compartilhamento eletrônico','fusão nuclear','transferência de nêutrons','perda de massa'],0,'ligações'],
  ['Balancear uma equação expressa a conservação:',['da temperatura','dos átomos','do volume','da pressão'],1,'reações'],
  ['Na equação 2H₂ + O₂ → 2H₂O, a proporção H₂:O₂ é:',['1:1','1:2','2:1','2:2'],2,'estequiometria'],
  ['A unidade mol conecta medidas macroscópicas:',['à quantidade de entidades','ao pH apenas','à cor','ao estado físico'],0,'estequiometria'],
  ['pH 3, comparado a pH 5, indica solução:',['mais básica','mais ácida','sempre neutra','sem íons'],1,'soluções'],
  ['Água transparente pode ser considerada potável sem análise?',['Sempre','Só se estiver fria','Não','Só em recipiente limpo'],2,'ambiente'],
  ['Um catalisador aumenta a velocidade porque:',['eleva a massa','reduz a energia de ativação','vira produto','aumenta o pH sempre'],1,'cinética'],
  ['Uma reação exotérmica:',['absorve calor do ambiente','libera energia ao ambiente','não troca energia','ocorre apenas com chama'],1,'energia'],
  ['Oxidação envolve, no modelo eletrônico:',['ganho de elétrons','perda de elétrons','ganho de nêutrons','perda de prótons'],1,'eletroquímica']
];

const $=s=>document.querySelector(s);const $$=s=>[...document.querySelectorAll(s)];
let completed=new Set(JSON.parse(localStorage.getItem('chemical-progress')||'[]'));
const grid=$('#lessonGrid');
function renderLessons(){grid.innerHTML=lessons.map(l=>`<article class="lesson-card ${completed.has(l.id)?'completed':''}"><span class="number">${l.n}</span><span class="tag">${l.bncc}</span><h3>${l.title}</h3><p>${l.summary}</p><button data-lesson="${l.id}">Abrir aula • ${l.time}</button></article>`).join('');$$('[data-lesson]').forEach(b=>b.onclick=()=>openLesson(b.dataset.lesson));updateProgress()}
function openLesson(id){const l=lessons.find(x=>x.id===id);$('#lessonContent').innerHTML=`<p class="eyebrow">AULA ${l.n}</p><h2>${l.title}</h2><div class="lesson-meta"><span>${l.time}</span><span>BNCC ${l.bncc}</span></div><article class="lesson-body">${l.body}</article><div class="lesson-actions"><button class="button primary" id="completeLesson">${completed.has(id)?'Aula concluída ✓':'Marcar como concluída'}</button></div>`;$('#lessonPanel').classList.remove('hidden');document.body.style.overflow='hidden';$('#completeLesson').onclick=()=>{completed.add(id);localStorage.setItem('chemical-progress',JSON.stringify([...completed]));renderLessons();$('#completeLesson').textContent='Aula concluída ✓'}}
$('#closeLesson').onclick=()=>{$('#lessonPanel').classList.add('hidden');document.body.style.overflow=''};
function updateProgress(){const pct=Math.round(completed.size/lessons.length*100);$('#progress').value=pct;$('#progressLabel').textContent=`${pct}%`}
$('#menuBtn').onclick=()=>{const nav=$('#nav');nav.classList.toggle('open');$('#menuBtn').setAttribute('aria-expanded',nav.classList.contains('open'))};$$('#nav a').forEach(a=>a.onclick=()=>$('#nav').classList.remove('open'));

const atomCanvas=$('#atomCanvas'),actx=atomCanvas.getContext('2d');let atomFrame=0;
const symbols=['','H','He','Li','Be','B','C','N','O','F','Ne','Na','Mg','Al','Si','P','S','Cl','Ar'];
function atomData(){return {p:+$('#protons').value,n:+$('#neutrons').value,e:+$('#electrons').value}}
function drawAtom(){const {p,n,e}=atomData(),w=atomCanvas.width,h=atomCanvas.height,cx=w/2,cy=h/2;actx.clearRect(0,0,w,h);actx.fillStyle='#071a2b';actx.fillRect(0,0,w,h);const shells=[Math.min(e,2),Math.min(Math.max(e-2,0),8),Math.min(Math.max(e-10,0),8)];shells.forEach((count,i)=>{if(!count)return;const r=62+i*55;actx.strokeStyle='rgba(105,230,220,.35)';actx.lineWidth=2;actx.beginPath();actx.arc(cx,cy,r,0,Math.PI*2);actx.stroke();for(let j=0;j<count;j++){const a=atomFrame*(.012-i*.002)+j*Math.PI*2/count;actx.fillStyle='#79a9ff';actx.beginPath();actx.arc(cx+Math.cos(a)*r,cy+Math.sin(a)*r,7,0,Math.PI*2);actx.fill()}});for(let i=0;i<p+n;i++){const a=i*2.399,r=5*Math.sqrt(i),x=cx+Math.cos(a)*r,y=cy+Math.sin(a)*r;actx.fillStyle=i%2?'#ef6a63':'#69e6dc';actx.beginPath();actx.arc(x,y,10,0,Math.PI*2);actx.fill()}actx.fillStyle='white';actx.font='700 18px system-ui';actx.textAlign='center';actx.fillText(symbols[p]||'?',cx,cy+6);atomFrame++;requestAnimationFrame(drawAtom)}
function updateAtom(){const {p,n,e}=atomData(),charge=p-e,status=$('#atomCharge');$('#pValue').textContent=p;$('#nValue').textContent=n;$('#eValue').textContent=e;status.textContent=charge===0?'neutro':charge>0?`cátion +${charge}`:`ânion ${charge}`;status.className=`status ${charge===0?'neutral':charge>0?'positive':'negative'}`;$('#atomReading').textContent=`${symbols[p]||'Elemento'} • número de massa ${p+n} • ${p} prótons, ${n} nêutrons e ${e} elétrons.`}
['protons','neutrons','electrons'].forEach(id=>$(`#${id}`).oninput=updateAtom);updateAtom();drawAtom();

const matterCanvas=$('#matterCanvas'),mctx=matterCanvas.getContext('2d');let particles=Array.from({length:42},(_,i)=>({x:35+(i%7)*72,y:200+Math.floor(i/7)*20,vx:(Math.random()-.5)*2,vy:(Math.random()-.5)*2}));
function stateFor(t){return t<=0?'sólido':t>=100?'gasoso':'líquido'}
function drawMatter(){const t=+$('#temperature').value,state=stateFor(t),speed=state==='sólido'?.15:state==='líquido'?1.2:3; mctx.fillStyle='#071a2b';mctx.fillRect(0,0,matterCanvas.width,matterCanvas.height);particles.forEach((p,i)=>{if(state==='sólido'){const tx=55+(i%7)*68,ty=185+Math.floor(i/7)*22;p.x+=(tx-p.x)*.08+(Math.random()-.5)*speed;p.y+=(ty-p.y)*.08+(Math.random()-.5)*speed}else{p.vx+=(Math.random()-.5)*.12;p.vy+=(Math.random()-.5)*.12;const mag=Math.hypot(p.vx,p.vy)||1;p.vx=p.vx/mag*speed;p.vy=p.vy/mag*speed;p.x+=p.vx;p.y+=p.vy;if(state==='líquido')p.y+=(230-p.y)*.01;if(p.x<15||p.x>505)p.vx*=-1;if(p.y<15||p.y>315)p.vy*=-1;p.x=Math.max(15,Math.min(505,p.x));p.y=Math.max(15,Math.min(315,p.y))}mctx.fillStyle=state==='gasoso'?'#c7f464':'#69e6dc';mctx.beginPath();mctx.arc(p.x,p.y,7,0,Math.PI*2);mctx.fill()});requestAnimationFrame(drawMatter)}
function updateMatter(){const t=+$('#temperature').value,state=stateFor(t);$('#tempLabel').textContent=`${t} °C`;$('#matterReading').textContent=`Estado predominante no modelo: ${state}. ${state==='sólido'?'Partículas vibram em posições organizadas.':state==='líquido'?'Partículas próximas mudam de posição.':'Partículas muito afastadas ocupam o recipiente.'}`}
$('#temperature').oninput=updateMatter;updateMatter();drawMatter();

let currentElement;function elementRound(){currentElement=elements[Math.floor(Math.random()*elements.length)];$('#elementClue').textContent=currentElement.clue;const wrong=elements.filter(e=>e!==currentElement).sort(()=>Math.random()-.5).slice(0,3),opts=[currentElement,...wrong].sort(()=>Math.random()-.5);$('#elementOptions').innerHTML=opts.map(e=>`<button type="button" data-symbol="${e.s}">${e.s} — ${e.name}</button>`).join('');$('#elementFeedback').textContent='';$$('[data-symbol]').forEach(b=>b.onclick=()=>{const ok=b.dataset.symbol===currentElement.s;$('#elementFeedback').textContent=ok?'Correto! A pista combina com número atômico, família ou aplicação.':`Ainda não. A resposta é ${currentElement.s} — ${currentElement.name}.`;$('#elementFeedback').className=`feedback ${ok?'ok':'bad'}`})}$('#nextElement').onclick=elementRound;elementRound();
$('#checkBalance').onclick=()=>{const [a,b,c]=['coefA','coefB','coefC'].map(id=>+$(`#${id}`).value),ok=2*a===2*c&&2*b===c;$('#balanceFeedback').textContent=ok?`Correto: ${a} H₂ + ${b} O₂ → ${c} H₂O conserva H e O.`:'Ainda não: conte separadamente H e O nos dois lados. A menor proporção inteira é 2 : 1 : 2.';$('#balanceFeedback').className=`feedback ${ok?'ok':'bad'}`};

let activeQuiz=[];$('#startQuiz').onclick=()=>{activeQuiz=[...questions].sort(()=>Math.random()-.5).slice(0,10);$('#quizIntro').classList.add('hidden');$('#quizResult').classList.add('hidden');const f=$('#quizForm');f.innerHTML=activeQuiz.map((q,i)=>`<article class="quiz-question"><fieldset><legend>${i+1}. ${q[0]}</legend>${q[1].map((o,j)=>`<label><input type="radio" name="q${i}" value="${j}" required> ${o}</label>`).join('')}</fieldset></article>`).join('')+`<button class="button primary" type="submit">Corrigir avaliação</button>`;f.classList.remove('hidden');f.scrollIntoView({behavior:'smooth'})};
$('#quizForm').onsubmit=e=>{e.preventDefault();const fd=new FormData(e.target),wrong=[];let score=0;activeQuiz.forEach((q,i)=>{if(+fd.get(`q${i}`)===q[2])score++;else wrong.push(q[3])});const pct=score*10;localStorage.setItem('chemical-last-score',score);$('#quizResult').innerHTML=`<h3>Resultado: ${score}/10 (${pct}%)</h3><p>${score>=8?'Ótimo domínio dos conceitos essenciais.':score>=6?'Boa base; revise os temas indicados.':'Use o resultado como mapa de estudo e tente novamente.'}</p>${wrong.length?`<p><b>Revisar:</b> ${[...new Set(wrong)].join(', ')}.</p>`:''}<button class="button ghost" id="retryQuiz">Refazer com novas questões</button>`;$('#quizResult').classList.remove('hidden');$('#retryQuiz').onclick=()=>$('#startQuiz').click();$('#quizResult').scrollIntoView({behavior:'smooth'})};
renderLessons();
